### ISSUE TITLE
binkd резолвит несуществующие адреса

### ISSUE THREAD

**Issue by askovpen** [pgul/binkd#22]
это баг или фича? :-)

```
+ 07 Nov 19:01:13 [1937773] call to 2:5020/9696.111@fidonet
+ 07 Nov 19:01:13 [1937772] getaddrinfo failed: Name or service not known (-2)
  07 Nov 19:01:13 [1937773] trying p111.f9696.n5020.z2.binkp.net [204.74.99.100]...
```
откуда взялся 204.74.99.100? днс про такой резолв не в курсе.

**Comment by pgul** [comment]
Вторая строка от другого процесса или потока, она не относится к этой сессии.
Резолв был, binkd не мог сам придумать этот IP.
Тут фишка в том, что f9696.n5020.z2.binkp.net - это cname на skovpen.org, соответственно и резолвинг для p111.f9696.n5020.z2.binkp.net запрашивается не у NS-ов зоны binkp.net, а по NS-ам skovpen.org. Не могу сходу сообразить, правильно это или нет, и если нет, то как это можно было бы исправить.
Наверное, проще считать, что это правильно. :)

**Comment by askovpen** [comment]
оказалось всё намного проще. пришлось strace'ом посмотреть, что он делает. 
он резолвит p111.f9696.n5020.z2.binkp.net - получает хер. дальше он резолвит p111.f9696.n5020.z2.binkp.net.org - получает что получает. Прописал ему домен поиска, чтобы такой херней не занимался.

**Comment by pgul** [comment]
Интересно, спасибо.
Возможно, имеет смысл прописать по умолчанию
```
root-domain binkp.net.
```
(с точкой) или добавлять точку при резолвинге, чтобы он игнорировал search domains. Вряд ли кто-то этим осознанно пользуется.
