### ISSUE TITLE
Port number in host specification is ignored, and TCP port 0 is used instead

### ISSUE THREAD

**Issue by bjorn-wiberg** [pgul/binkd#27]
Hello,

I'm using binkd 1.1a-99-1 on Debian Buster, x86_64.
I reported this as https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=983096 but the package maintainer asked me to forward the information to you.
I'm hoping that the bug is also relevant for the latest binkd version and that you can easily reproduce it simply by adding a port number to an existing host specification.
(If not, I'd have to assume that the bug has disappeared in more recent versions of binkd, and that it will propagate to Debian in due time.)

A short description of the problem:

When specifying a port number in the host:port specification for a node, the port number appears to be ignored during polls -- binkd tries to use port number 0(!) as the destination port:

```
ftn@glimmer:~$ /usr/sbin/binkd -c -v -P21:1/100@fsxnet /etc/binkd/binkd.cfg
  12:04 [8603] BEGIN, binkd/1.1a-99/Linux -c -v -P21:1/100@fsxnet /etc/binkd/binkd.cfg
  12:04 [8603] creating a poll for 21:1/100@fsxnet (`d' flavour)
  12:04 [8603] clientmgr started
$ -d 21:1/100@fsxnet
+ 12:04 [8604] call to 21:1/100@fsxnet
  12:04 [8604] trying net1.fsxnet.nz [219.89.83.33]:0...
? 12:04 [8604] connection to 21:1/100@fsxnet failed: Connection timed out
  12:04 [8604] trying net1.fsxnet.nz [2001:470:d:123::50]:0...
? 12:04 [8604] connection to 21:1/100@fsxnet failed: No route to host
  12:04 [8603] rc(8604)=0
$ -d 21:1/100@fsxnet    busy
  -- 618:500/1@micronet busy
  -- 77:1/100@scinet    busy
$ -d 21:1/100@fsxnet
+ 12:06 [8713] call to 21:1/100@fsxnet
  12:06 [8713] trying net1.fsxnet.nz [219.89.83.33]:0...
? 12:06 [8713] connection to 21:1/100@fsxnet failed: Connection timed out
  12:06 [8713] trying net1.fsxnet.nz [2001:470:d:123::50]:0...
? 12:06 [8713] connection to 21:1/100@fsxnet failed: No route to host
  12:06 [8603] rc(8713)=0
! 12:06 [8603] got signal #2.
ftn@glimmer:~$
```

netstat output shows:

```
root@glimmer:~# netstat -anp | grep SYN
tcp        0      1 192.168.1.5:42058       219.89.83.33:*          SYN_SENT    8760/binkd: call to
```

I would have expected the specified port number (24556) to be used.
Removing the port number makes binkd use the default binkp port (24554).

Attaching the config files.

I have verified with strace that the config file is read and that /etc/ifmail/passwds is also read.
I have also tried replacing "password /etc/ifmail/passwds" with a more complete /etc/binkd/binkd.inc (including passwords there instead) but with the same result.

Best regards
Björn

**Comment by bjorn-wiberg** [comment]
[/etc/binkd/binkd.cfg](https://github.com/pgul/binkd/files/6017485/binkd.cfg.txt)
[/etc/binkd/binkd.inc](https://github.com/pgul/binkd/files/6017486/binkd.inc.txt)
[/etc/ifmail/passwds](https://github.com/pgul/binkd/files/6017487/passwds.txt)

**Comment by bjorn-wiberg** [comment]
An update after some more experimentation:

It appears that the hostname "net1.fsxnet.nz" causes problems when combined with a port number, e.g. "net1.fsxnet.nz:24556".
Same thing with "net2.fsxnet.nz" combined with a port number, e.g. "net2.fsxnet.nz:24556".

**Something special about "net" combined with a number when used with getnameinfo()** (in client.c)?

Another hostname "agency.fsxnet.nz" (which resolves to the exact same IPs) works just fine with port numbers, e.g. "agency.fsxnet.nz:24556".

And everything works fine when not specifying port numbers, e.g. "net1.fsxnet.nz".

**Comment by streaps** [comment]
use a newer version. this is a known bug.

**Comment by streaps** [comment]
Can we close this issue?

**Comment by bjorn-wiberg** [comment]
> Can we close this issue?

Yes, closing it. (As you pointed out, this has been fixed in later versions.)
